### ISSUE TITLE
关于中英翻译的问题

### ISSUE THREAD

**Issue by xiao-zhang** [yanwii/machine-translation#1]
大佬你好，我用你的这种方式做了实验，自定义问题，英中翻译没问题，BLEU值也可以达到30分左右，但是当我在问题名称后面加了‘_rev‘’实现中英翻译时，效果却很差，BLEU值才17分左右，不知道为什么，希望大佬可以指点指点，非常感谢！

**Comment by xiao-zhang** [comment]
两个翻译模型都是训练了30w步，中英翻译时，中文用了分字和分词两种方式，效果都不好，泪奔了~

**Comment by yanwii** [comment]
中英翻译相对难一点，建议你各种方式都尝试一下，英文分词采用纯正的bpe分词方式，可以参考 **subword-nmt** 项目

**Comment by xiao-zhang** [comment]
谢谢啦，刚刚试了bpe的方式，效果确实好很多。

**Comment by xiao-zhang** [comment]
非常感谢，这两天多试了几种方式，解决啦

**Comment by 528031207** [comment]
我也在做中译英请问大佬用的什么方法呀，我现在也挺痛苦的效果也很差。尝试了很多方法都不好，还望大佬指点一下呀！!
